# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
u1 = User.create(:image => 'http://res.cloudinary.com/dbenxy2yz/image/upload/v1526546905/entertainment-2013-01-bill-murray-bill-murray-300.jpg', :name => 'Bill1', :email => 'bill1@gmail.com', :location => 'Melbourne',  :password => 'bill1', :description => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',:keyskills => 'rails, react',:githubu =>'https://github.com/SarabjitBansal' )
u2 = User.create(:image => 'http://res.cloudinary.com/dbenxy2yz/image/upload/v1526546905/51janjhtTwL._SY445_.jpg', :name => 'Bill2', :email => 'bill2@gmail.com', :location => 'Elizabeth Bay', :password => 'bill2',:description => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',:keyskills => 'react')
u3 = User.create(:image => 'http://res.cloudinary.com/dbenxy2yz/image/upload/v1526546909/o-bill-facebook.jpg', :name => 'Bill3', :email => 'bill3@gmail.com', :location => 'Woollahra',  :password => 'bill3',:description => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',:keyskills => 'javascript')
