development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # this one works after deployment on heroku
  # url: redis://localhost:6379/1
  url: redis://localhost:3333/cable
  # channel_prefix: prj_server_production
url: <%= ENV["REDIS_URL"] %>
